--!strict
--[[
	Famille "decor" — la décoration et l'acoustique.

	Ces objets n'ont presque aucun effet technique, sauf l'acoustique. Leur
	rôle est de porter le STYLE et de remplir le fond. C'est là que le
	joueur exprime son identité, et c'est aussi là qu'il peut tout gâcher
	en accumulant.

	Les objets d'acoustique sont l'exception : ils agissent sur la qualité
	sonore, qui est le facteur de rétention le plus sous-estimé. Une image
	moyenne se pardonne, un son moyen fait fermer l'onglet.
]]

return {
	-- ── Acoustique ────────────────────────────────────────────────────────
	{
		id = "acoustic_panels",
		name = "Panneaux acoustiques x6",
		brand = "Auvox",
		family = "decor",
		category = "acoustic",
		style = "pro",
		tier = 2,
		price = 150,
		acoustic = 0.5,
		power = 0,
		surface = "wall",
		footprint = Vector2.new(4.8, 0.3),
		height = 3.2,
		description = "Mousse alvéolée sur le mur. Supprime l'écho de la pièce vide et affiche clairement que tu prends ça au sérieux.",
	},
	{
		id = "acoustic_bass_traps",
		name = "Pièges à basses d'angle",
		brand = "Auvox",
		family = "decor",
		category = "acoustic",
		style = "pro",
		tier = 3,
		price = 280,
		acoustic = 0.35,
		power = 0,
		surface = "floor",
		footprint = Vector2.new(0.9, 0.9),
		height = 6,
		description = "Dans les angles, là où le son s'accumule. Personne ne les remarquera, et tout le monde entendra la différence.",
	},
	{
		id = "heavy_curtain",
		name = "Rideau lourd occultant",
		brand = "Fibre & Co",
		family = "decor",
		category = "acoustic",
		style = "cosy",
		tier = 1,
		price = 65,
		acoustic = 0.3,
		power = 0,
		surface = "wall",
		footprint = Vector2.new(3.6, 0.3),
		height = 6.5,
		description = "Absorbe le son, bloque la lumière du jour, et fait un fond uni très correct. Trois usages pour soixante euros.",
	},
	{
		id = "thick_rug",
		name = "Tapis épais",
		brand = "Fibre & Co",
		family = "decor",
		category = "acoustic",
		style = "cosy",
		tier = 1,
		price = 80,
		acoustic = 0.25,
		power = 0,
		surface = "floor",
		footprint = Vector2.new(5.5, 4),
		height = 0.1,
		description = "Coupe la réverbération au sol et réchauffe une pièce carrelée, visuellement comme acoustiquement.",
	},

	-- ── Décoration murale ─────────────────────────────────────────────────
	{
		id = "poster_game",
		name = "Affiche de jeu",
		brand = "générique",
		family = "decor",
		category = "wall",
		style = "gamer",
		tier = 1,
		price = 15,
		power = 0,
		surface = "wall",
		footprint = Vector2.new(1.6, 0.1),
		height = 2.3,
		description = "Le premier objet que tout le monde accroche. Utile pour combler un mur vide, dangereux quand il y en a douze.",
	},
	{
		id = "poster_film_vintage",
		name = "Affiche de cinéma encadrée",
		brand = "générique",
		family = "decor",
		category = "wall",
		style = "retro",
		tier = 2,
		price = 70,
		power = 0,
		surface = "wall",
		footprint = Vector2.new(1.8, 0.12),
		height = 2.5,
		description = "Encadrée, jaunie, choisie. Elle raconte quelque chose sur toi, ce qu'une affiche scotchée ne fait pas.",
	},
	{
		id = "wall_panels_wood",
		name = "Lambris bois clair",
		brand = "Fibre & Co",
		family = "decor",
		category = "wall",
		style = "sobre",
		tier = 2,
		price = 210,
		power = 0,
		surface = "wall",
		footprint = Vector2.new(8, 0.2),
		height = 6,
		description = "Recouvre un mur entier. Change une chambre en décor d'un seul achat, et pardonne beaucoup de fautes de goût.",
	},
	{
		id = "framed_milestones",
		name = "Cadres de paliers",
		brand = "générique",
		family = "decor",
		category = "wall",
		style = "pro",
		tier = 2,
		price = 90,
		power = 0,
		surface = "wall",
		footprint = Vector2.new(3, 0.1),
		height = 1.6,
		description = "Tes paliers d'abonnés encadrés au mur. Se remplissent tout seuls au fil de la partie, et c'est ce qui les rend satisfaisants.",
	},

	-- ── Objets ────────────────────────────────────────────────────────────
	{
		id = "plant_small",
		name = "Plante en pot",
		brand = "générique",
		family = "decor",
		category = "object",
		style = "sobre",
		tier = 1,
		price = 25,
		power = 0,
		surface = "floor",
		footprint = Vector2.new(0.8, 0.8),
		height = 1.4,
		description = "Du vert dans le cadre. C'est bête, ça marche, et ça rend n'importe quel fond plus vivant.",
	},
	{
		id = "plant_large",
		name = "Grande plante d'intérieur",
		brand = "générique",
		family = "decor",
		category = "object",
		style = "sobre",
		tier = 2,
		price = 90,
		power = 0,
		surface = "floor",
		footprint = Vector2.new(1.4, 1.4),
		height = 3,
		description = "Remplit un angle vide derrière toi. Le meuble le moins cher qui donne l'air d'avoir un décor.",
	},
	{
		id = "figures_shelf",
		name = "Collection de figurines",
		brand = "générique",
		family = "decor",
		category = "object",
		style = "gamer",
		tier = 1,
		price = 60,
		power = 0,
		surface = "desk",
		footprint = Vector2.new(1.6, 0.5),
		height = 0.7,
		description = "À poser sur une étagère derrière toi. Le chat les commentera plus que ton contenu.",
	},
	{
		id = "bookshelf_full",
		name = "Bibliothèque garnie",
		brand = "Fibre & Co",
		family = "decor",
		category = "object",
		style = "cosy",
		tier = 2,
		price = 260,
		power = 0,
		surface = "floor",
		footprint = Vector2.new(3.2, 1.2),
		height = 5.5,
		description = "Le fond préféré des gens qui veulent avoir l'air fiables. Ça fonctionne, et tout le monde le sait.",
	},
	{
		id = "crt_stack",
		name = "Pile de téléviseurs cathodiques",
		brand = "brocante",
		family = "decor",
		category = "object",
		style = "retro",
		tier = 2,
		price = 180,
		power = 0,
		surface = "floor",
		footprint = Vector2.new(2, 1.6),
		height = 2.8,
		description = "Empilés dans un coin, éteints, purement décoratifs. Personne ne sait pourquoi c'est si beau, mais ça l'est.",
	},
	{
		id = "arcade_cabinet",
		name = "Borne d'arcade",
		brand = "brocante",
		family = "decor",
		category = "object",
		style = "retro",
		tier = 3,
		price = 1400,
		power = 180,
		surface = "floor",
		footprint = Vector2.new(2.6, 2.6),
		height = 6.5,
		description = "Énorme, lourde, chère, et absolument imbattable dans un fond de plan large. Un achat de coeur qui se justifie tout seul à l'image.",
	},
	{
		id = "mini_fridge",
		name = "Mini-frigo",
		brand = "Hexar",
		family = "decor",
		category = "object",
		style = "gamer",
		tier = 1,
		price = 110,
		power = 65,
		surface = "floor",
		footprint = Vector2.new(1.6, 1.6),
		height = 2,
		description = "À portée de main pour ne jamais quitter le siège. C'est exactement le problème, et c'est pour ça que tu vas l'acheter.",
	},
}
