--!strict
--[[
	Famille "furniture" — le mobilier.

	Le bureau est la pièce la plus structurante du jeu : sa largeur décide
	du nombre d'écrans qu'on peut poser devant soi, donc de ce qu'on peut
	surveiller pendant un direct. Le fauteuil décide de la vitesse à
	laquelle la fatigue monte.
]]

return {
	-- ── Bureaux ───────────────────────────────────────────────────────────
	{
		id = "desk_family",
		name = "Bureau de la chambre",
		brand = "hérité",
		family = "furniture",
		category = "desk",
		style = "sobre",
		tier = 1,
		price = 0,
		power = 0,
		surface = "floor",
		footprint = Vector2.new(9, 4),
		deskSlots = 6,
		cableManagement = false,
		description = "Celui sur lequel tu as fait tes devoirs. Il a une rayure que tu ne peux pas expliquer à tes parents.",
	},
	{
		id = "desk_wide",
		name = "Plan de travail 160",
		brand = "Fibre & Co",
		family = "furniture",
		category = "desk",
		style = "sobre",
		tier = 2,
		price = 240,
		power = 0,
		surface = "floor",
		footprint = Vector2.new(13, 5),
		deskSlots = 10,
		cableManagement = true,
		description = "Large, avec un chemin de câbles sous le plateau. On ne voit plus la pieuvre par-dessous.",
	},
	{
		id = "desk_sit_stand",
		name = "Bureau assis-debout",
		brand = "Fibre & Co",
		family = "furniture",
		category = "desk",
		style = "pro",
		tier = 3,
		price = 690,
		power = 40,
		surface = "floor",
		footprint = Vector2.new(14, 5),
		deskSlots = 12,
		cableManagement = true,
		fatigueRelief = 0.15,
		description = "Se relève pour streamer debout. Ralentit la fatigue sur les longues sessions, et impressionne les invités.",
	},
	{
		id = "desk_gaming_rgb",
		name = "Bureau gaming Vantage",
		brand = "Hexar",
		family = "furniture",
		category = "desk",
		style = "gamer",
		tier = 2,
		price = 320,
		power = 15,
		surface = "floor",
		footprint = Vector2.new(12, 5),
		deskSlots = 9,
		cableManagement = true,
		description = "Bords rétroéclairés, surface carbone, porte-casque intégré. Assumé.",
	},

	-- ── Sièges ────────────────────────────────────────────────────────────
	{
		id = "chair_kitchen",
		name = "Chaise de cuisine",
		brand = "hérité",
		family = "furniture",
		category = "chair",
		style = "sobre",
		tier = 1,
		price = 0,
		power = 0,
		surface = "floor",
		footprint = Vector2.new(3, 3),
		fatigueRelief = -0.1,
		description = "Ton dos t'en reparlera dans dix ans. Il commence déjà, en fait.",
	},
	{
		id = "chair_gaming",
		name = "Siège Hexar Racer",
		brand = "Hexar",
		family = "furniture",
		category = "chair",
		style = "gamer",
		tier = 2,
		price = 260,
		power = 0,
		surface = "floor",
		footprint = Vector2.new(4, 4),
		fatigueRelief = 0.1,
		description = "Coutures rouges, coussin lombaire, forme de baquet. Confortable deux heures, discutable après huit.",
	},
	{
		id = "chair_ergonomic",
		name = "Fauteuil ergonomique maillé",
		brand = "Fibre & Co",
		family = "furniture",
		category = "chair",
		style = "pro",
		tier = 3,
		price = 780,
		power = 0,
		surface = "floor",
		footprint = Vector2.new(4, 4),
		fatigueRelief = 0.3,
		description = "Laid en photo, irremplaçable au bout de six heures. Le meilleur rapport confort-prix du catalogue, et personne ne l'achète en premier.",
	},

	-- ── Rangements et surfaces ────────────────────────────────────────────
	{
		id = "shelf_low",
		name = "Meuble bas 2 cases",
		brand = "Fibre & Co",
		family = "furniture",
		category = "storage",
		style = "sobre",
		tier = 1,
		price = 70,
		power = 0,
		surface = "floor",
		footprint = Vector2.new(6, 3),
		description = "Range ce qui traîne, et offre une étagère de plus dans le champ de la caméra.",
	},
	{
		id = "shelf_wall",
		name = "Étagère murale bois",
		brand = "Fibre & Co",
		family = "furniture",
		category = "storage",
		style = "cosy",
		tier = 1,
		price = 45,
		power = 0,
		surface = "wall",
		footprint = Vector2.new(7, 1),
		description = "Se pose derrière toi et se remplit d'objets. C'est la couche la plus facile pour composer un fond.",
	},
	{
		id = "shelf_display_lit",
		name = "Vitrine rétroéclairée",
		brand = "Hexar",
		family = "furniture",
		category = "storage",
		style = "gamer",
		tier = 3,
		price = 420,
		power = 30,
		surface = "floor",
		footprint = Vector2.new(5, 8),
		description = "Une vitrine haute, éclairée par le fond, pour exposer ce que tu collectionnes. Très photogénique, très encombrante.",
	},

	-- ── Zones du local ────────────────────────────────────────────────────
	{
		id = "guest_table",
		name = "Table d'invités 3 places",
		brand = "Fibre & Co",
		family = "furniture",
		category = "guest",
		style = "pro",
		tier = 2,
		price = 480,
		power = 0,
		surface = "floor",
		footprint = Vector2.new(12, 6),
		seats = 3,
		description = "Le meuble qui transforme une chaîne en émission. Trois personnes en face, et le format change tout seul.",
	},
	{
		id = "sofa_lounge",
		name = "Canapé de plateau",
		brand = "Fibre & Co",
		family = "furniture",
		category = "guest",
		style = "cosy",
		tier = 2,
		price = 540,
		power = 0,
		surface = "floor",
		footprint = Vector2.new(11, 5),
		seats = 3,
		description = "Pour les segments assis, détendus, où l'invité parle plus qu'il ne l'avait prévu.",
	},
	{
		id = "audience_bench",
		name = "Gradin de public 10 places",
		brand = "Cadran",
		family = "furniture",
		category = "audience",
		style = "pro",
		tier = 3,
		price = 1200,
		power = 0,
		surface = "floor",
		footprint = Vector2.new(16, 8),
		seats = 10,
		description = "Un public dans le studio change le rythme d'une émission. Il rit, ou il ne rit pas, et ça s'entend à l'antenne.",
	},
}
