--!strict
--[[
	Famille "lighting" — l'éclairage, fonctionnel et décoratif.

	Les luminaires fonctionnels agissent par leur POSITION RÉELLE : une
	source mal placée nuit au lieu d'aider. Un contre-jour sans lumière de
	face donne une silhouette noire, et c'est mérité.

	Les luminaires décoratifs qui portent `controllable = true` se
	rattachent au hub LED et deviennent pilotables : ambiances nommées,
	liaison à une scène, assignation à une touche de Stream Deck.
]]

return {
	-- ── Éclairage fonctionnel ─────────────────────────────────────────────
	{
		id = "light_ring",
		name = "Anneau lumineux 12 pouces",
		brand = "Cadran",
		family = "lighting",
		category = "key",
		style = "gamer",
		tier = 1,
		price = 45,
		quality = 0.3,
		requires = { "power" },
		power = 18,
		surface = "desk",
		footprint = Vector2.new(1.6, 1.6),
		height = 5,
		description = "Éclaire ton visage et te met deux donuts dans les yeux. Tout le monde commence par là.",
	},
	{
		id = "light_softbox",
		name = "Softbox 60x60",
		brand = "Cadran",
		family = "lighting",
		category = "key",
		style = "pro",
		tier = 2,
		price = 130,
		quality = 0.7,
		requires = { "power" },
		power = 60,
		surface = "floor",
		footprint = Vector2.new(2.4, 2.4),
		height = 6,
		description = "Lumière douce et large, à poser à quarante-cinq degrés. Prend la place d'un fauteuil.",
	},
	{
		id = "light_panel_bi",
		name = "Panneau LED bicolore",
		brand = "Orell",
		family = "lighting",
		category = "key",
		style = "pro",
		tier = 3,
		price = 340,
		quality = 0.9,
		requires = { "power" },
		power = 75,
		surface = "floor",
		footprint = Vector2.new(2.2, 1),
		height = 6,
		controllable = true,
		description = "Température réglable du chaud au froid. Se pilote depuis le hub, donc la lumière suit la scène.",
	},
	{
		id = "light_fill",
		name = "Lampe d'appoint diffusée",
		brand = "Cadran",
		family = "lighting",
		category = "fill",
		style = "sobre",
		tier = 1,
		price = 55,
		quality = 0.4,
		requires = { "power" },
		power = 25,
		surface = "floor",
		footprint = Vector2.new(1.4, 1.4),
		height = 5,
		description = "Se met de l'autre côté du visage pour adoucir les ombres. Personne ne la remarque, et c'est le but.",
	},
	{
		id = "light_rim",
		name = "Barre de contre-jour",
		brand = "Orell",
		family = "lighting",
		category = "rim",
		style = "pro",
		tier = 2,
		price = 110,
		quality = 0.6,
		requires = { "power" },
		power = 30,
		surface = "floor",
		footprint = Vector2.new(0.8, 0.8),
		height = 5.5,
		controllable = true,
		description = "Derrière toi, elle détache ta silhouette du fond. Sans lumière de face, elle fait de toi une ombre chinoise.",
	},
	{
		id = "light_backdrop",
		name = "Rampe pour fond vert",
		brand = "Cadran",
		family = "lighting",
		category = "backdrop",
		style = "pro",
		tier = 2,
		price = 160,
		quality = 0.75,
		requires = { "power" },
		power = 55,
		surface = "floor",
		footprint = Vector2.new(4, 0.8),
		height = 2,
		description = "Éclaire le fond vert de façon uniforme. Sans elle, l'incrustation bave quel que soit le prix du fond.",
	},

	-- ── Le hub ────────────────────────────────────────────────────────────
	{
		id = "led_hub",
		name = "Hub d'ambiance Lumen",
		brand = "Lumen",
		family = "lighting",
		category = "hub",
		style = "gamer",
		tier = 2,
		price = 90,
		requires = { "usb", "power" },
		power = 5,
		surface = "desk",
		footprint = Vector2.new(0.7, 0.5),
		height = 0.2,
		visible = false,
		description = "Regroupe tous les luminaires pilotables de la pièce et permet d'enregistrer des ambiances. Sans lui, tes LED sont juste allumées.",
	},

	-- ── Éclairage décoratif pilotable ─────────────────────────────────────
	{
		id = "led_strip",
		name = "Bandeau LED 5 m",
		brand = "Lumen",
		family = "lighting",
		category = "led",
		style = "gamer",
		tier = 1,
		price = 30,
		requires = { "power" },
		power = 20,
		surface = "wall",
		footprint = Vector2.new(8, 0.15),
		height = 0.15,
		controllable = true,
		description = "Se colle derrière un meuble ou le long d'une plinthe. Le premier achat déco de tout le monde, et il fonctionne.",
	},
	{
		id = "led_bars",
		name = "Barres verticales x2",
		brand = "Lumen",
		family = "lighting",
		category = "led",
		style = "gamer",
		tier = 2,
		price = 140,
		requires = { "power" },
		power = 35,
		surface = "floor",
		footprint = Vector2.new(0.5, 0.5),
		height = 5,
		controllable = true,
		description = "Deux colonnes de couleur de part et d'autre du cadre. C'est ce qui fait qu'un fond a l'air composé plutôt que subi.",
	},
	{
		id = "led_hexagons",
		name = "Panneaux hexagonaux x9",
		brand = "Lumen",
		family = "lighting",
		category = "led",
		style = "gamer",
		tier = 2,
		price = 190,
		requires = { "power" },
		power = 45,
		surface = "wall",
		footprint = Vector2.new(3.6, 0.2),
		height = 3.2,
		controllable = true,
		description = "Se composent en nid d'abeille sur le mur. Reconnaissables entre mille, ce qui est un avantage et un risque.",
	},
	{
		id = "neon_pseudo",
		name = "Néon à ton pseudo",
		brand = "Lumen",
		family = "lighting",
		category = "led",
		style = "gamer",
		tier = 2,
		price = 220,
		requires = { "power" },
		power = 25,
		surface = "wall",
		footprint = Vector2.new(3.6, 0.2),
		height = 1.2,
		controllable = true,
		description = "Ton nom en lettres lumineuses au-dessus de ton épaule. Prétentieux jusqu'au jour où les gens le reconnaissent.",
	},
	{
		id = "fairy_lights",
		name = "Guirlande lumineuse chaude",
		brand = "Lumen",
		family = "lighting",
		category = "led",
		style = "cosy",
		tier = 1,
		price = 20,
		requires = { "power" },
		power = 10,
		surface = "wall",
		footprint = Vector2.new(6, 0.15),
		height = 2.4,
		controllable = true,
		description = "Petites ampoules chaudes en cascade. Le raccourci le plus court vers une ambiance intime.",
	},
	{
		id = "lamp_desk_warm",
		name = "Lampe de bureau articulée",
		brand = "Fibre & Co",
		family = "lighting",
		category = "led",
		style = "sobre",
		tier = 1,
		price = 40,
		requires = { "power" },
		power = 15,
		surface = "desk",
		footprint = Vector2.new(0.6, 0.6),
		height = 1.6,
		description = "Une vraie lampe, pour vraiment travailler. Chaude, orientable, discrète à l'image.",
	},

	-- ── Écrans décoratifs ─────────────────────────────────────────────────
	{
		id = "deco_screen_small",
		name = "Écran d'ambiance 15 pouces",
		brand = "Novaris",
		family = "lighting",
		category = "decoscreen",
		style = "gamer",
		tier = 2,
		price = 180,
		requires = { "hdmi", "power" },
		power = 20,
		surface = "wall",
		footprint = Vector2.new(1.6, 0.2),
		height = 0.95,
		controllable = true,
		description = "Un petit écran posé dans le décor, qui affiche ton logo, un compteur d'abonnés ou une animation. Il attire l'oeil sans voler la vedette.",
	},
	{
		id = "deco_screen_wall",
		name = "Mur d'écrans 2x2",
		brand = "Novaris",
		family = "lighting",
		category = "decoscreen",
		style = "pro",
		tier = 3,
		price = 1600,
		requires = { "hdmi", "power" },
		power = 160,
		surface = "wall",
		footprint = Vector2.new(5.2, 0.25),
		height = 3,
		controllable = true,
		description = "Quatre dalles derrière toi, pilotées depuis la régie. C'est le décor des vraies émissions, et ça se voit immédiatement à l'image.",
	},
}
