--!strict
--[[
	Famille "tech" — le matériel qui fait exister le stream.

	Ces objets sont fonctionnels avant d'être décoratifs, mais ils sont
	visibles à l'image et portent donc quand même un style.
]]

return {
	-- ── Caméras ───────────────────────────────────────────────────────────
	{
		id = "cam_attic",
		name = "LifeCam 480",
		brand = "Genelux",
		family = "tech",
		category = "camera",
		style = "sobre",
		tier = 1,
		price = 0,
		quality = 0.15,
		requires = { "usb" },
		power = 2,
		surface = "desk",
		footprint = Vector2.new(0.4, 0.4),
		height = 0.5,
		description = "Elle était dans un carton au grenier. Elle fait le travail, si on est indulgent sur le mot travail.",
	},
	{
		id = "cam_streamcam",
		name = "StreamCam C7",
		brand = "Genelux",
		family = "tech",
		category = "camera",
		style = "gamer",
		tier = 2,
		price = 120,
		quality = 0.45,
		requires = { "usb" },
		power = 3,
		surface = "desk",
		footprint = Vector2.new(0.45, 0.45),
		height = 0.55,
		description = "La webcam que tout le monde a. Correcte partout, excellente nulle part.",
	},
	{
		id = "cam_mirrorless",
		name = "Hybride A6 + capture",
		brand = "Orell",
		family = "tech",
		category = "camera",
		style = "pro",
		tier = 3,
		price = 980,
		quality = 0.9,
		requires = { "hdmi", "power" },
		power = 12,
		surface = "desk",
		footprint = Vector2.new(1, 1),
		height = 1.4,
		description = "Un vrai appareil photo sur trépied. Le flou d'arrière-plan fait la moitié du travail à ta place.",
	},

	-- ── Micros ────────────────────────────────────────────────────────────
	{
		id = "mic_headset",
		name = "Casque-micro G1",
		brand = "Genelux",
		family = "tech",
		category = "microphone",
		style = "gamer",
		tier = 1,
		price = 0,
		quality = 0.2,
		requires = { "jack" },
		power = 0,
		surface = "desk",
		footprint = Vector2.new(0.7, 0.7),
		height = 1,
		description = "Capte ta voix, ta respiration, ton clavier, et ton frère dans le couloir.",
	},
	{
		id = "mic_usb",
		name = "Podium USB",
		brand = "Auvox",
		family = "tech",
		category = "microphone",
		style = "retro",
		tier = 2,
		price = 95,
		quality = 0.5,
		requires = { "usb" },
		power = 2,
		surface = "desk",
		footprint = Vector2.new(0.7, 0.7),
		height = 1.5,
		description = "Le micro qui a lancé mille podcasts. Le pied prend de la place sur le bureau.",
	},
	{
		id = "mic_xlr_arm",
		name = "Cardio XLR + bras",
		brand = "Auvox",
		family = "tech",
		category = "microphone",
		style = "pro",
		tier = 3,
		price = 340,
		quality = 0.85,
		requires = { "xlr" },
		power = 0,
		surface = "desk",
		footprint = Vector2.new(0.6, 0.6),
		height = 1.2,
		description = "Suspendu, donc le bureau reste libre. Demande une interface audio, que personne ne pense à acheter du premier coup.",
	},
	{
		id = "audio_interface",
		name = "Interface 2 voies",
		brand = "Auvox",
		family = "tech",
		category = "audio",
		style = "pro",
		tier = 2,
		price = 180,
		quality = 0.7,
		requires = { "usb", "power" },
		provides = { "xlr" },
		power = 8,
		surface = "desk",
		footprint = Vector2.new(0.9, 0.7),
		height = 0.3,
		description = "La boîte qui transforme un micro de studio en quelque chose que l'ordinateur comprend.",
	},

	-- ── Machines ──────────────────────────────────────────────────────────
	{
		id = "pc_handmedown",
		name = "Tour de récup",
		brand = "assemblage maison",
		family = "tech",
		category = "computer",
		style = "sobre",
		tier = 1,
		price = 0,
		quality = 0.1,
		requires = { "power" },
		provides = { "usb", "hdmi", "jack" },
		power = 220,
		surface = "floor",
		footprint = Vector2.new(0.8, 1.8),
		height = 1.9,
		description = "Démarre en quatre-vingt-dix secondes. Ventile comme un sèche-cheveux. Tiendra, probablement.",
	},
	{
		id = "pc_midrange",
		name = "Atelier 5600",
		brand = "Novaris",
		family = "tech",
		category = "computer",
		style = "gamer",
		tier = 2,
		price = 850,
		quality = 0.55,
		requires = { "power" },
		provides = { "usb", "hdmi", "jack", "ethernet" },
		power = 400,
		surface = "floor",
		footprint = Vector2.new(0.85, 1.9),
		height = 2,
		description = "Encode sans broncher. Ne t'empêchera plus de faire quoi que ce soit.",
	},
	{
		id = "pc_workstation",
		name = "Station Novaris Pro",
		brand = "Novaris",
		family = "tech",
		category = "computer",
		style = "pro",
		tier = 3,
		price = 2400,
		quality = 0.95,
		requires = { "power" },
		provides = { "usb", "hdmi", "jack", "ethernet" },
		power = 650,
		surface = "floor",
		footprint = Vector2.new(1, 2.1),
		height = 2.3,
		description = "Silencieuse, ce qui est plus rare et plus cher que puissante. Le boot passe sous les cinq secondes.",
	},

	-- ── Écrans ────────────────────────────────────────────────────────────
	{
		id = "monitor_starter",
		name = "Écran 22 pouces récupéré",
		brand = "hérité",
		family = "tech",
		category = "display",
		style = "sobre",
		tier = 1,
		price = 0,
		quality = 0.25,
		requires = { "hdmi", "power" },
		power = 22,
		surface = "desk",
		footprint = Vector2.new(3, 0.3),
		height = 1.7,
		screens = 1,
		description = "Un rémanent d'image en haut à gauche que tu ne remarques plus. Il affiche, c'est déjà ça.",
	},
	{
		id = "monitor_24",
		name = "Écran 24 pouces",
		brand = "Novaris",
		family = "tech",
		category = "display",
		style = "sobre",
		tier = 1,
		price = 140,
		quality = 0.4,
		requires = { "hdmi", "power" },
		power = 25,
		surface = "desk",
		footprint = Vector2.new(3.3, 0.3),
		height = 1.85,
		screens = 1,
		description = "Un écran. Le deuxième change plus ta vie que le premier ne l'a fait.",
	},
	{
		id = "monitor_27_ips",
		name = "Écran 27 pouces IPS",
		brand = "Novaris",
		family = "tech",
		category = "display",
		style = "pro",
		tier = 2,
		price = 290,
		quality = 0.65,
		requires = { "hdmi", "power" },
		power = 32,
		surface = "desk",
		footprint = Vector2.new(3.7, 0.3),
		height = 2.1,
		screens = 1,
		description = "Des couleurs justes. On ne s'en rend compte qu'en revenant à l'ancien.",
	},
	{
		id = "monitor_vertical",
		name = "Écran vertical 24 pouces",
		brand = "Novaris",
		family = "tech",
		category = "display",
		style = "pro",
		tier = 2,
		price = 220,
		quality = 0.5,
		requires = { "hdmi", "power" },
		power = 26,
		surface = "desk",
		footprint = Vector2.new(1.9, 0.3),
		height = 3.3,
		screens = 1,
		description = "Pivoté à la verticale. Fait pour le chat, et pour rien d'autre.",
	},

	-- ── Périphériques ─────────────────────────────────────────────────────
	{
		id = "kb_membrane",
		name = "Clavier de bureau",
		brand = "hérité",
		family = "tech",
		category = "keyboard",
		style = "sobre",
		tier = 1,
		price = 0,
		requires = { "usb" },
		power = 1,
		surface = "desk",
		footprint = Vector2.new(1.8, 0.7),
		height = 0.15,
		description = "Trois touches sont luisantes, les autres non. On devine lesquelles.",
	},
	{
		id = "mouse_basic",
		name = "Souris filaire",
		brand = "hérité",
		family = "tech",
		category = "mouse",
		style = "sobre",
		tier = 1,
		price = 0,
		requires = { "usb" },
		power = 1,
		surface = "desk",
		footprint = Vector2.new(0.35, 0.6),
		height = 0.2,
		description = "Le fil s'accroche au coin du bureau à chaque mouvement brusque.",
	},
	{
		id = "kb_mecha",
		name = "Clavier mécanique Hexar",
		brand = "Hexar",
		family = "tech",
		category = "keyboard",
		style = "gamer",
		tier = 2,
		price = 90,
		requires = { "usb" },
		power = 3,
		surface = "desk",
		footprint = Vector2.new(1.8, 0.7),
		height = 0.22,
		description = "Switches bruyants, rétroéclairage par touche. Le micro les entendra, tes viewers aussi.",
	},
	{
		id = "mouse_gaming",
		name = "Souris Hexar 8K",
		brand = "Hexar",
		family = "tech",
		category = "mouse",
		style = "gamer",
		tier = 2,
		price = 65,
		requires = { "usb" },
		power = 2,
		surface = "desk",
		footprint = Vector2.new(0.4, 0.65),
		height = 0.25,
		description = "Onze boutons dont tu en utiliseras deux. Les neuf autres sont pour la photo du setup.",
	},
	{
		id = "deskmat",
		name = "Grand tapis de bureau",
		brand = "Hexar",
		family = "tech",
		category = "deskmat",
		style = "gamer",
		tier = 1,
		price = 25,
		power = 0,
		surface = "desk",
		footprint = Vector2.new(3.4, 1.6),
		height = 0.05,
		description = "Couvre tout le plateau. Unifie le bureau d'un seul achat, et cache les rayures.",
	},
	{
		id = "headphone_stand",
		name = "Support de casque",
		brand = "Fibre & Co",
		family = "tech",
		category = "stand",
		style = "sobre",
		tier = 1,
		price = 20,
		power = 0,
		surface = "desk",
		footprint = Vector2.new(0.5, 0.5),
		height = 1.2,
		description = "Libère un coin de bureau et donne au setup un air rangé qu'il ne mérite pas forcément.",
	},

	-- ── Régie et pilotage ─────────────────────────────────────────────────
	{
		id = "deck_mini",
		name = "Deck Mini",
		brand = "Cadran",
		family = "tech",
		category = "streamdeck",
		style = "gamer",
		tier = 1,
		price = 80,
		keys = 6,
		requires = { "usb" },
		power = 3,
		surface = "desk",
		footprint = Vector2.new(0.5, 0.4),
		height = 0.15,
		description = "Six touches. De quoi couper son micro sans chercher la fenêtre, ce qui vaut déjà son prix.",
	},
	{
		id = "deck_standard",
		name = "Deck 15",
		brand = "Cadran",
		family = "tech",
		category = "streamdeck",
		style = "gamer",
		tier = 2,
		price = 190,
		keys = 15,
		requires = { "usb" },
		power = 5,
		surface = "desk",
		footprint = Vector2.new(0.75, 0.55),
		height = 0.15,
		description = "Quinze touches et des pages. On commence à piloter sans jamais quitter le direct des yeux.",
	},
	{
		id = "deck_xl",
		name = "Deck XL",
		brand = "Cadran",
		family = "tech",
		category = "streamdeck",
		style = "pro",
		tier = 3,
		price = 380,
		keys = 32,
		requires = { "usb" },
		power = 8,
		surface = "desk",
		footprint = Vector2.new(1.1, 0.65),
		height = 0.15,
		description = "Trente-deux touches. À ce stade tu ne streames plus, tu réalises.",
	},
	{
		id = "capture_card",
		name = "Carte d'acquisition 4K",
		brand = "Orell",
		family = "tech",
		category = "capture",
		style = "pro",
		tier = 2,
		price = 210,
		quality = 0.8,
		requires = { "usb" },
		provides = { "hdmi" },
		power = 6,
		surface = "desk",
		footprint = Vector2.new(0.6, 0.4),
		height = 0.15,
		description = "Fait entrer une console ou une caméra dans l'ordinateur. Ouvre une source de plus dans KZ Studio.",
	},

	-- ── Fonds ─────────────────────────────────────────────────────────────
	{
		id = "green_small",
		name = "Fond vert 1,5 m",
		brand = "Cadran",
		family = "tech",
		category = "backdrop",
		style = "pro",
		tier = 1,
		price = 60,
		quality = 0.4,
		power = 0,
		surface = "wall",
		footprint = Vector2.new(6, 0.15),
		height = 6,
		description = "Suffisant si tu ne bouges pas. Tu bougeras.",
	},
	{
		id = "green_large",
		name = "Fond vert 3 m sur pieds",
		brand = "Cadran",
		family = "tech",
		category = "backdrop",
		style = "pro",
		tier = 2,
		price = 210,
		quality = 0.8,
		power = 0,
		surface = "floor",
		footprint = Vector2.new(12, 0.4),
		height = 9,
		description = "Couvre largement le cadre. Encore faut-il avoir trois mètres de mur libre.",
	},
}
