// Kayzx Studio — les vraies données (projets, frise, marque, références). window.KS_DONNEES.
// Les vidéos des projets Kayzx TV sont servies par la page (window.KS_MEDIAS, rempli à la publication).
window.KS_DONNEES = {
  projets: [
    {
      id: 'intro', titre: 'Intro de stream Kayzx TV', statut: 'fait', date: '8 oct. 2026',
      duree: '35 s', format: '1080p · 60 i/s', images: 2100, media: 'intro',
      resume: 'L’intro qui lance chaque live : une régie crédible, des compteurs, un portail de particules, un coffre à code, puis le logo.',
      couleurs: ['#061C1B', '#0F3D3A', '#E3A83B', '#C9D1D1'],
      chiffres: [['35 s', 'durée'], ['2 100', 'images'], ['60 i/s', 'fluidité'], ['0', 'musique (choix)']],
      techniques: ['Interface de régie crédible', 'Compteurs à rouleaux', 'Typo éditoriale en italique', 'Portail de particules', 'Flou de mouvement'],
      appris: ['Chaque image est une fonction du temps : on la rend image par image dans Chromium.', 'Capture PNG rapide : 4 fois plus vite que la capture standard.', 'L’envoi dans la conversation est limité à 30 Mo : compression en deux passes.'],
      prompt: 'Reprends l’intro Kayzx TV (dossier intro/) et fais-en une version de 15 s pour les shorts, au format 9:16, avec les mêmes couleurs et la même typo.',
    },
    {
      id: 'attente', titre: 'Écran d’attente en boucle', statut: 'fait', date: '9 oct. 2026',
      duree: '1 min 30', format: 'Boucle sans couture · 3D', images: 5400, media: 'attente',
      resume: 'L’écran « Le live commence bientôt » : un studio en 3D, une grille lumineuse, une régie d’écrans, des particules qui reforment le logo. Il boucle à l’infini sans qu’on voie la reprise.',
      couleurs: ['#061C1B', '#1F6F66', '#5FA89C', '#E3A83B'],
      chiffres: [['90 s', 'boucle'], ['5 400', 'images'], ['26 000', 'particules'], ['81', 'bruitages']],
      techniques: ['Three.js (WebGL)', 'Boucle parfaite sur 90 s', 'Régie d’écrans flottants', 'Bruitages synthétisés', 'Curseur qui coche une check-list'],
      appris: ['En rendu sans écran, le WebGL passe par un moteur logiciel : il faut compter environ 1 h.', 'Tout ce qui bouge est périodique sur 90 s, et la dernière image rejoint la première.', 'Des clics et des notifications suffisent à rendre l’attente vivante, sans musique.'],
      prompt: 'Reprends l’écran d’attente (dossier attente/) et fais une variante « Pause, on revient vite » de 60 s en boucle, avec le même studio 3D.',
    },
    {
      id: 'ligue1', titre: 'Promo Ligue 1+ saison 27/28', statut: 'fait', date: '9 oct. 2026',
      duree: '46 s', format: '1080p · 60 i/s', images: 2760, media: null, local: true,
      resume: 'Une promo d’abonnement dans le langage visuel de Ligue 1+ : faisceaux diagonaux, plans du site officiel, chiffres et offres. Test perso, gardé hors ligne.',
      couleurs: ['#0B0B0B', '#085FFF', '#50AAFF', '#FFFFFF'],
      chiffres: [['46 s', 'durée'], ['2 760', 'images'], ['7', 'plans vidéo'], ['3', 'volets de transition']],
      techniques: ['Faisceaux en diagonale', 'Volets inclinés', 'Plans vidéo extraits image par image', 'Typo condensée officielle'],
      appris: ['Le Chromium de rendu ne lit pas le H.264 : on extrait les plans en JPEG.', 'Couper un plan juste avant le texte incrusté de la source.'],
      prompt: 'Reprends la promo Ligue 1+ (dossier ligue1/) et fais une version verticale 9:16 de 20 s.',
    },
    {
      id: 'gta-demo', titre: 'Démo GTA 6 en équipe d’agents', statut: 'arrete', date: '8 oct. 2026',
      duree: '2 min 15 prévues', format: 'Storyboard', images: 0, media: null, local: true,
      resume: 'Une longue démo à plans lents, fabriquée par une équipe d’agents. Arrêtée : trop longue à produire agent par agent. Le storyboard et les recherches ont servi à la promo GTA VI.',
      couleurs: ['#1D002E', '#9A39BB', '#FF775C', '#FF9745'],
      chiffres: [['7', 'actes'], ['35', 'plans repérés'], ['2 min 15', 'prévues'], ['1', 'leçon']],
      techniques: ['Storyboard plan par plan', 'Repérage des coupes', 'Équipe d’agents'],
      appris: ['Déléguer la recherche, garder la fabrication au même endroit.', 'Un message envoyé pendant le travail peut arrêter les agents en cours.'],
      prompt: 'Reprends le storyboard de gta6/storyboard.md et propose une version de 45 s centrée sur Vice City.',
    },
    {
      id: 'gta', titre: 'Promo de lancement GTA VI', statut: 'fait', date: '9 oct. 2026',
      duree: '1 min 15', format: '1080p · 60 i/s', images: 4530, media: null, local: true,
      resume: 'Une pub de grand média pour la sortie : régions, personnages, records de vues, éditions et prix, collector, radios, date. Caméra continue et raccords en mouvement. Test perso, gardé hors ligne.',
      couleurs: ['#14021F', '#3F45BB', '#E25790', '#FF9745'],
      chiffres: [['75,5 s', 'durée'], ['4 530', 'images'], ['129,7', 'BPM'], ['70', 'bruitages']],
      techniques: ['Caméra virtuelle continue', 'Zooms traversants', 'Flou de mouvement adaptatif', 'Interface éclairée (pastilles, compteurs)', 'Égaliseur sur la vraie musique'],
      appris: ['Couper au milieu d’un mouvement rapide rend la coupe invisible.', 'Le flou de mouvement seulement sur les passages rapides : même rendu, deux fois moins cher.', 'Vérifier chaque chiffre avant de l’animer.'],
      prompt: 'Reprends la promo GTA VI (dossier gta6/promo/) et fais un teaser vertical de 20 s pour TikTok avec les trois plans les plus forts.',
    },
  ],
  frise: [
    { quand: '8 oct. · 18:06', titre: 'Intro de stream Kayzx TV', texte: '35 s, ta première intro.' },
    { quand: '8 oct. · 18:44', titre: 'Références gardées', texte: 'Tes liens de motion deviennent une méthode.' },
    { quand: '8 oct. · 19:28', titre: 'Storyboard GTA 6', texte: 'Le plan d’une démo de 2 min 15.' },
    { quand: '9 oct. · 10:17', titre: 'Promo Ligue 1+', texte: '46 s pour la saison 27/28.' },
    { quand: '9 oct. · 11:17', titre: 'Écran d’attente', texte: 'Boucle de 1 min 30 en 3D.' },
    { quand: '9 oct. · 13:13', titre: 'Vocabulaire du mouvement', texte: 'Les 10 effets, nommés.' },
    { quand: '9 oct. · 15:02', titre: 'Promo GTA VI', texte: 'La pub de lancement, version 1.' },
    { quand: '9 oct. · 16:40', titre: 'GTA VI, version 2', texte: 'Caméra continue et flou de mouvement.' },
    { quand: '9 oct. · aujourd’hui', titre: 'Kayzx Studio', texte: 'Cet espace de travail.' },
  ],
  marque: {
    nom: 'Kayzx TV',
    couleurs: [
      ['Encre', '#061C1B'], ['Forest teal', '#0F3D3A'], ['Teal', '#1F6F66'], ['Sauge', '#5FA89C'],
      ['Honey gold', '#E3A83B'], ['Or clair', '#F2C76E'], ['Mist gray', '#C9D1D1'], ['Blanc brume', '#EEF2F1'],
    ],
    polices: [
      ['Titres', 'Insatiable Display', 'Condensée et puissante (licence Ligue 1+, usage perso).'],
      ['Texte', 'Inter Tight', 'Nette et compacte, pour les sous-titres et les cartes.'],
      ['Données', 'JetBrains Mono', 'Pour les compteurs, l’heure et les étiquettes de régie.'],
    ],
    regles: ['Tout est en français.', 'Pas de musique sur l’intro : les bruitages suffisent.', 'Un point doré avant le nom, jamais d’autre ornement.', 'Les médias officiels (jeux, ligues) restent hors ligne.'],
  },
  references: [
    { cat: 'video', titre: 'Showreel', auteur: 'Leon Abboud', lien: 'https://x.com/leonabboud/status/2103576084499358051', garde: 'Un cadre fixe et une scène par technique.', tags: ['Cadre de régie', 'Titres masqués', 'Chiffres qui défilent'] },
    { cat: 'video', titre: 'Agenda qui se remplit', auteur: 'Clément', lien: 'https://x.com/cleeeeeeeeement/status/2108222854948917514', garde: 'Une vraie interface qui se remplit toute seule.', tags: ['Interface crédible', 'Compteurs', 'Dézoom final'] },
    { cat: 'video', titre: 'BlueVisa', auteur: 'THISMA', lien: 'https://x.com/thismacapital/status/2104173625079451934', garde: 'Les titres mot par mot, un mot clé souligné.', tags: ['Texte révélé', 'Cartes qui se cochent'] },
    { cat: 'video', titre: 'Fastlane', auteur: 'Gaurav', lien: 'https://x.com/gauravsbuilding/status/2104370091672711402', garde: 'Le plafond actuel : 12 h de travail continu.', tags: ['Tunnel de vignettes', 'Chiffres LED', 'Sol réfléchissant'] },
    { cat: 'video', titre: 'Identité Framer', auteur: 'Gal Shir', lien: 'https://x.com/galshirart/status/1975920588372771249', garde: 'Un logo construit sur sa grille, en verre et en métal.', tags: ['Extrusion 3D', 'Lettres qui se resserrent'] },
    { cat: 'video', titre: 'Interface Opal', auteur: 'Nicolas (Scalyx)', lien: 'https://www.tiktok.com/@nicolas.scalyx/video/7691950536492371233', garde: 'Des éléments qui brillent dans le noir, sous une douche de lumière.', tags: ['Interface éclairée', 'Formes qui se divisent', 'Mise au point'] },
    { cat: 'video', titre: 'Promo ChatGPT', auteur: 'qasim_motion', lien: 'https://www.tiktok.com/@qasim_motion/video/7667165306426526996', garde: 'Le bouton devient la photo, qui devient le monde.', tags: ['Zoom traversant', 'Caméra qui suit'] },
    { cat: 'video', titre: 'Motion pour Claude', auteur: 'zensu.visuals', lien: 'https://www.tiktok.com/@zensu.visuals/video/7670123707980991776', garde: 'Une seule prise : la caméra ne coupe jamais.', tags: ['Caméra continue', 'Flou de mouvement', 'Carte en 3D'] },
    { cat: 'outil', titre: 'Sites animés dans Figma', auteur: 'Viktor Oddy', lien: 'https://x.com/viktoroddy/status/2070831152248901804', garde: 'Héros plein écran, masques de texte, cartes qui se déploient.', tags: ['Masques de texte', 'Cartes verticales'] },
    { cat: 'outil', titre: '10 effets de défilement', auteur: 'Vox', lien: 'https://x.com/voxyz_ai/status/2108324058739745228', garde: 'Le vocabulaire commun pour décrire un mouvement.', tags: ['Vocabulaire', 'Méthode'] },
    { cat: 'outil', titre: 'Skills de design', auteur: 'Harshil Tomar', lien: 'https://x.com/Hartdrawss/status/2108490179199570077', garde: 'Les skills installés pour des interfaces plus soignées.', tags: ['Apple design', 'Revue de design'] },
    { cat: 'outil', titre: 'prompt-motion.com', auteur: 'Galerie', lien: 'https://prompt-motion.com', garde: 'Des motions faits par IA, avec leur prompt.', tags: ['Prompts', 'Techniques'] },
    { cat: 'galerie', titre: 'motionsites.ai', auteur: 'Galerie', lien: 'http://motionsites.ai', garde: '600 sites 3D et 500 fonds animés.', tags: ['Sites 3D'] },
    { cat: 'galerie', titre: '60fps.design', auteur: 'Galerie', lien: 'http://60fps.design', garde: 'Les micro-animations qui font « cher ».', tags: ['Micro-animations'] },
    { cat: 'galerie', titre: 'navbar.gallery', auteur: 'Galerie', lien: 'http://navbar.gallery', garde: 'Des barres de navigation.', tags: ['Navigation'] },
    { cat: 'galerie', titre: 'footer.design', auteur: 'Galerie', lien: 'http://footer.design', garde: 'Des pieds de page.', tags: ['Pied de page'] },
    { cat: 'galerie', titre: 'cta.gallery', auteur: 'Galerie', lien: 'http://cta.gallery', garde: 'Des boutons d’appel à l’action.', tags: ['Boutons'] },
    { cat: 'galerie', titre: '404s.design', auteur: 'Galerie', lien: 'http://404s.design', garde: 'Des pages 404.', tags: ['Pages d’erreur'] },
    { cat: 'galerie', titre: 'unsection.com', auteur: 'Galerie', lien: 'http://unsection.com', garde: 'Des sections de site complètes.', tags: ['Sections'] },
    { cat: 'galerie', titre: 'bentogrids.com', auteur: 'Galerie', lien: 'http://bentogrids.com', garde: 'Des grilles « bento ».', tags: ['Grilles'] },
    { cat: 'outil', titre: 'Galeries de design', auteur: 'Viktor Oddy', lien: 'https://x.com/viktoroddy/status/2099152986102796467', garde: 'La liste de galeries à consulter.', tags: ['Ressources'] },
  ],
};
